"""

Django settings for bridge2capital project.



Generated by 'django-admin startproject' using Django 3.0.7.



For more information on this file, see

https://docs.djangoproject.com/en/3.0/topics/settings/



For the full list of settings and their values, see

https://docs.djangoproject.com/en/3.0/ref/settings/

"""



import os



# Build paths inside the project like this: os.path.join(BASE_DIR, ...)

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))





# Quick-start development settings - unsuitable for production

# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/



# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = 'uhfko0b562zbxdsjzypnn+h^c0auuw4x4i-1-em(!zvr#jzrx4'


ALLOWED_HOSTS = ['bridge2capital.com','www.bridge2capital.com','*']





# Application definition



INSTALLED_APPS = [

    'jet',

    'django.contrib.admin',

    'django.contrib.auth',

    'django.contrib.contenttypes',

    'django.contrib.sessions',

    'django.contrib.messages',

    'django.contrib.staticfiles',

    'ckeditor',

    'english',

    'django_otp',

    'django_otp.plugins.otp_totp',

    'favicon',

    'hindi',

]



MIDDLEWARE = [

    'django.middleware.security.SecurityMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',

    'django.middleware.common.CommonMiddleware',

    'django.middleware.csrf.CsrfViewMiddleware',

    'django.contrib.auth.middleware.AuthenticationMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',

    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'django_otp.middleware.OTPMiddleware',

]



ROOT_URLCONF = 'bridge2capital.urls'



TEMPLATES = [

    {

        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        'DIRS': [os.path.join(BASE_DIR, 'templates')],

        'APP_DIRS': True,

        'OPTIONS': {

            'context_processors': [

                'django.template.context_processors.debug',

                'django.template.context_processors.request',

                'django.contrib.auth.context_processors.auth',

                'django.contrib.messages.context_processors.messages',

            ],

        },

    },

]



WSGI_APPLICATION = 'bridge2capital.wsgi.application'





# Database

# https://docs.djangoproject.com/en/3.0/ref/settings/#databases



DATABASES = {

    'default': {

        'ENGINE': 'django.db.backends.mysql',

        'NAME': 'bridgeca_testing',

        'USER': 'Sanyam',

        'PASSWORD': '1234',

        'HOST': 'localhost',

        'PORT': 3306

    },

    'OPTIONS':{

        'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",

    }

}





# Password validation

# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators



AUTH_PASSWORD_VALIDATORS = [

    {

        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',

    },

    {

        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',

    },

    {

        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',

    },

    {

        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',

    },

]





# Internationalization

# https://docs.djangoproject.com/en/3.0/topics/i18n/



LANGUAGE_CODE = 'en-us'



TIME_ZONE = 'Asia/Kolkata'



USE_I18N = True



USE_L10N = True



USE_TZ = True





# Static files (CSS, JavaScript, Images)

# https://docs.djangoproject.com/en/3.0/howto/static-files/

ENVIRONMENT_RUNNING = 'local'       # 'local' / 'qa' / 'prod'

# Doing this because the file structure different for each environment
if ENVIRONMENT_RUNNING == 'local':
    STATIC_ROOT = os.path.join(os.path.dirname(BASE_DIR), 'uatResources', 'static') 
    STATIC_URL = '/static/'
    MEDIA_URL = '/media/'
    MEDIA_ROOT = os.path.join(os.path.dirname(BASE_DIR), 'uatResources', 'media') 
    STATICFILES_DIRS = [
        os.path.join(BASE_DIR, "static"),
    # '/var/www/static/',
    ]

    DEBUG = True

elif ENVIRONMENT_RUNNING == 'qa':
    STATIC_URL = '/static/'
    STATIC_ROOT = '/home/bridgeca/uat-website.bridge2capital.com/static/'
    STATICFILES_DIRS = [
        os.path.join(BASE_DIR, 'static'),
    #    '/var/www/static/',
    ]
    MEDIA_URL = '/media/'
    MEDIA_ROOT = '/home/bridgeca/uat-website.bridge2capital.com/media/'

    DEBUG = True

elif ENVIRONMENT_RUNNING == 'prod':
    STATIC_ROOT = '/home/bridgeca/public_html/static/'
    STATIC_URL = '/static/'
    MEDIA_URL = '/media/'
    MEDIA_ROOT = '/home/bridgeca/public_html/media/'
    STATICFILES_DIRS = [
        os.path.join(BASE_DIR, "static"),
    # '/var/www/static/',
    ]

    DEBUG = False

else:
    raise EnvironmentError(f'{ENVIRONMENT_RUNNING} not implemented! Use any of these: local, qa, prod')



EMAIL_HOST = 'mail.xtracapindia.com'

EMAIL_PORT = '25'

EMAIL_HOST_USER = 'noreply@xtracapindia.com'

EMAIL_HOST_PASSWORD = '1RKu_8$9uR2w'

# EMAIL_USE_TLS = True

EMAIL_USE_SSL = False



CKEDITOR_CONFIGS = {

    'default': {

        # 'skin': 'moono',

        'skin': 'moono-lisa',

        'toolbar_Basic': [

            ['Source', '-', 'Bold', 'Italic']

        ],

        'toolbar_YourCustomToolbarConfig': [

            {'name': 'document', 'items': ['Source', '-', 'Save', 'NewPage', 'Preview', 'Print', '-', 'Templates']},

            {'name': 'clipboard', 'items': ['Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo']},

            {'name': 'editing', 'items': ['Find', 'Replace', '-', 'SelectAll']},

            {'name': 'forms',

             'items': ['Form', 'Checkbox', 'Radio', 'TextField', 'Textarea', 'Select', 'Button', 'ImageButton',

                       'HiddenField']},

            '/',

            {'name': 'basicstyles',

             'items': ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat']},

            {'name': 'paragraph',

             'items': ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote', 'CreateDiv', '-',

                       'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-', 'BidiLtr', 'BidiRtl',

                       'Language']},

            {'name': 'links', 'items': ['Link', 'Unlink', 'Anchor']},

            {'name': 'insert',

             'items': ['Image', 'Flash', 'Table', 'HorizontalRule', 'Smiley', 'SpecialChar', 'PageBreak', 'Iframe']},

            '/',

            {'name': 'styles', 'items': ['Styles', 'Format', 'Font', 'FontSize']},

            {'name': 'colors', 'items': ['TextColor', 'BGColor']},

            {'name': 'tools', 'items': ['Maximize', 'ShowBlocks']},

            {'name': 'about', 'items': ['About']},

            '/',  # put this to force next toolbar on new line

            {'name': 'yourcustomtools', 'items': [

                # put the name of your editor.ui.addButton here

                'Preview',

                'Maximize',



            ]},

        ],

        'toolbar': 'YourCustomToolbarConfig',  # put selected toolbar config here

        'toolbarGroups': [{ 'name': 'document', 'groups': [ 'mode', 'document', 'doctools' ] }],

        'height': 291,

        'width': '100%',

        'filebrowserWindowHeight': 725,

        'filebrowserWindowWidth': 940,

        'toolbarCanCollapse': True,

        'mathJaxLib': '//cdn.mathjax.org/mathjax/2.2-latest/MathJax.js?config=TeX-AMS_HTML',

        'tabSpaces': 4,

        'extraPlugins': ','.join([

            'uploadimage', # the upload image feature

            # your extra plugins here

            'div',

            'autolink',

            'autoembed',

            'embedsemantic',

            'autogrow',

            'devtools',

            'widget',

            'lineutils',

            'clipboard',

            'dialog',

            'dialogui',

            'elementspath',

        ]),

    }

}



JET_THEMES = [

    {

        'theme': 'default', # theme folder name

        'color': '#47bac1', # color of the theme's button in user menu

        'title': 'Default' # theme title

    },

    {

        'theme': 'green',

        'color': '#44b78b',

        'title': 'Green'

    },

    {

        'theme': 'light-green',

        'color': '#2faa60',

        'title': 'Light Green'

    },

    {

        'theme': 'light-violet',

        'color': '#a464c4',

        'title': 'Light Violet'

    },

    {

        'theme': 'light-blue',

        'color': '#5EADDE',

        'title': 'Light Blue'

    },

    {

        'theme': 'light-gray',

        'color': '#222',

        'title': 'Light Gray'

    }

]



JET_CHANGE_FORM_SIBLING_LINKS = True