# Generated by Django 3.0 on 2021-12-20 07:21

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsAlternateBusinessModelSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100000, verbose_name='Heading')),
                ('image', models.ImageField(upload_to='about_us/images', verbose_name='Image')),
                ('paragraph', ckeditor.fields.RichTextField(verbose_name='Paragraph')),
                ('language', models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English')], default='English', max_length=100)),
            ],
            options={
                'verbose_name': 'About Us: Business Model',
                'verbose_name_plural': 'About Us: Business Models',
                'db_table': 'about_us_alternatebusinessmodelsection',
            },
        ),
        migrations.CreateModel(
            name='AboutUsGreenBorderSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100000, verbose_name='Heading')),
                ('paragraph', models.CharField(max_length=1000000, verbose_name='Paragraph')),
                ('language', models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English')], default='English', max_length=100)),
            ],
            options={
                'verbose_name': 'About Us: Green Radius - Text Banner',
                'verbose_name_plural': 'About Us: Green Radius - Text Banner',
                'db_table': 'about_us_greenbordersection',
            },
        ),
        migrations.CreateModel(
            name='AboutUsMainBannerTwoButton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=10000, verbose_name='Heading')),
                ('paragraph1', models.CharField(max_length=1000000, verbose_name='Paragraph 1')),
                ('paragraph2', models.CharField(max_length=1000000, verbose_name='Paragraph 2')),
                ('paragraph3', models.CharField(max_length=1000000, verbose_name='Paragraph 3')),
                ('button1_text', models.CharField(max_length=100000, verbose_name='Button 1 - Text')),
                ('button2_text', models.CharField(blank=True, max_length=100000, verbose_name='Button 2 - Text')),
                ('button1_url', models.TextField(max_length=100000, verbose_name='Button 1 - URL')),
                ('button2_url', models.TextField(blank=True, max_length=100000, verbose_name='Button 2 - URL')),
                ('image', models.ImageField(upload_to='about_us/images')),
                ('language', models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English')], default='English', max_length=100)),
            ],
            options={
                'verbose_name': 'About Us: Main Banner - Two Button',
                'verbose_name_plural': 'About Us: Main Banner - Two Button',
                'db_table': 'about_us_mainbannertwobutton',
            },
        ),
        migrations.CreateModel(
            name='AboutUsMetaDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200000)),
                ('language', models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English')], default='English', max_length=100)),
            ],
            options={
                'verbose_name': 'About Us: Meta Description',
                'db_table': 'about_us_meta_description',
            },
        ),
        migrations.CreateModel(
            name='AboutUsMetaTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(blank=True, max_length=20000)),
                ('language', models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English')], default='English', max_length=100)),
            ],
            options={
                'verbose_name': 'About Us: Meta Tag',
                'db_table': 'about_us_meta_tag',
            },
        ),
        migrations.CreateModel(
            name='AboutUsOurStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100000, verbose_name='Heading')),
                ('paragraph1', models.CharField(max_length=1000000, verbose_name='Paragraph 1')),
                ('paragraph2', models.CharField(max_length=1000000, verbose_name='Paragraph 2')),
                ('image', models.ImageField(upload_to='about_us/images')),
                ('person1_name', models.CharField(max_length=100000, verbose_name='Person 1 - Left - Name')),
                ('person1_designation', models.CharField(max_length=100000, verbose_name='Person 1 - Left - Designation')),
                ('person2_name', models.CharField(blank=True, max_length=100000, verbose_name='Person 2 - Right - Name')),
                ('person2_designation', models.CharField(blank=True, max_length=100000, verbose_name='Person 2 - Right - Designation')),
                ('person3_name', models.CharField(blank=True, max_length=100000, verbose_name='Person 3 - Right - Name')),
                ('person3_designation', models.CharField(blank=True, max_length=100000, verbose_name='Person 3 - Right - Designation')),
                ('language', models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English')], default='English', max_length=100)),
            ],
            options={
                'verbose_name': 'About Us: Our Story',
                'verbose_name_plural': 'About Us: Our Story',
                'db_table': 'about_us_ourstory',
            },
        ),
        migrations.CreateModel(
            name='AboutUsOurStoryParagraphs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100000, verbose_name='Heading')),
                ('paragraph', ckeditor.fields.RichTextField()),
                ('language', models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English')], default='English', max_length=100)),
            ],
            options={
                'verbose_name': 'About Us: Our Story - Paragraphs',
                'verbose_name_plural': 'About Us: Our Story - Paragraphs',
                'db_table': 'about_us_ourstoryparagraphs',
            },
        ),
        migrations.CreateModel(
            name='AboutUsPageTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('language', models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English')], default='English', max_length=100)),
            ],
            options={
                'verbose_name': 'About Us: Page Title',
                'verbose_name_plural': 'About Us: Page Title',
                'db_table': 'about_us_pagetitle',
            },
        ),
        migrations.CreateModel(
            name='AboutUsUpcomingProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=1000, verbose_name='Product Name')),
                ('image', models.ImageField(upload_to='about_us/images', verbose_name='Logo')),
                ('step', models.CharField(max_length=10, verbose_name='Step')),
                ('description', models.CharField(max_length=1000, verbose_name='Product Description')),
                ('language', models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English')], default='English', max_length=100)),
            ],
            options={
                'verbose_name': 'About Us: Upcoming Product',
                'verbose_name_plural': 'About Us: Upcoming Products',
                'db_table': 'about_us_upcomingproducts',
            },
        ),
        migrations.CreateModel(
            name='ContactUsContactDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', ckeditor.fields.RichTextField()),
                ('contact', ckeditor.fields.RichTextField()),
                ('facebook_url', models.TextField(max_length=100000, verbose_name='Facebook URL')),
                ('linkedin_url', models.TextField(max_length=100000, verbose_name='Linkedin URL')),
                ('twitter_url', models.TextField(max_length=100000, verbose_name='Twitter URL')),
                ('language', models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English')], default='English', max_length=100)),
            ],
            options={
                'verbose_name': 'Contact Us: Contact Details',
                'verbose_name_plural': 'Contact Us: Contact Details',
                'db_table': 'contact_us_contactdetails',
            },
        ),
        migrations.CreateModel(
            name='ContactUsContactForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200, verbose_name='Full Name')),
                ('contactnumber', models.CharField(max_length=12, verbose_name='Contact Number')),
                ('email', models.EmailField(max_length=200, verbose_name='Email Address')),
                ('message', models.CharField(max_length=600, verbose_name='Message')),
                ('language', models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English')], default='English', max_length=100)),
            ],
            options={
                'verbose_name': 'Contact Us: Contact Form',
                'verbose_name_plural': 'Contact Us: Contact Form',
                'db_table': 'contact_us_contactform',
            },
        ),
        migrations.CreateModel(
            name='ContactUsMetaDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200000)),
                ('language', models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English')], default='English', max_length=100)),
            ],
            options={
                'verbose_name': 'Contact Us: Meta Description',
                'db_table': 'contact_us_meta_description',
            },
        ),
        migrations.CreateModel(
            name='ContactUsMetaTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(blank=True, max_length=20000)),
                ('language', models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English')], default='English', max_length=100)),
            ],
            options={
                'verbose_name': 'Contact Us: Meta Tag',
                'db_table': 'contact_us_meta_tag',
            },
        ),
        migrations.CreateModel(
            name='ContactUsPageTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('language', models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English')], default='English', max_length=100)),
            ],
            options={
                'verbose_name': 'Contact Us: Page Title',
                'verbose_name_plural': 'Contact Us: Page Title',
                'db_table': 'contact_us_pagetitle',
            },
        ),
        migrations.CreateModel(
            name='CreditLandingForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('number', models.TextField(blank=True, null=True)),
                ('business', models.TextField(blank=True, null=True)),
                ('product', models.TextField(blank=True, null=True)),
                ('gst', models.BooleanField(blank=True, default=False)),
                ('pan', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Credit Leads',
                'verbose_name_plural': 'Credit Leads',
                'db_table': 'credit_leads',
            },
        ),
        migrations.CreateModel(
            name='CreditProductMetaDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200000)),
                ('language', models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English')], default='English', max_length=100)),
            ],
            options={
                'verbose_name': 'Credit Product: Meta Description',
                'db_table': 'credit_product_meta_description',
            },
        ),
        migrations.CreateModel(
            name='CreditProductMetaTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(blank=True, max_length=20000)),
                ('language', models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English')], default='English', max_length=100)),
            ],
            options={
                'verbose_name': 'Credit Product: Meta Tag',
                'db_table': 'credit_product_meta_tag',
            },
        ),
        migrations.CreateModel(
            name='CreditProductOneButtonSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', ckeditor.fields.RichTextField(blank=True, verbose_name='Heading')),
                ('paragraph', ckeditor.fields.RichTextField(blank=True, verbose_name='Paragraph')),
                ('button1_text', models.CharField(blank=True, max_length=1000, verbose_name='Button 1 - Text')),
                ('button1_url', models.TextField(blank=True, max_length=10000)),
                ('image', models.ImageField(upload_to='credit_product/images')),
                ('alt_tag', models.CharField(max_length=1000, verbose_name='Image Alt Tag')),
                ('language', models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English')], default='English', max_length=100)),
            ],
            options={
                'verbose_name': 'Credit Product: Section 2 - One Button',
                'verbose_name_plural': 'Credit Product: Section 2 - One Button',
                'db_table': 'credit_product_onebuttonsection',
            },
        ),
        migrations.CreateModel(
            name='CreditProductPageTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('language', models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English')], default='English', max_length=100)),
            ],
            options={
                'verbose_name': 'Credit Product: Page Title',
                'verbose_name_plural': 'Credit Product: Page Title',
                'db_table': 'credit_product_pagetitle',
            },
        ),
        migrations.CreateModel(
            name='CreditProductProductFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='credit_product/images')),
                ('header', ckeditor.fields.RichTextField(verbose_name='Heading')),
                ('paragraph', ckeditor.fields.RichTextField(verbose_name='Paragraph')),
                ('language', models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English')], default='English', max_length=100)),
            ],
            options={
                'verbose_name': 'Credit Product: Product Features',
                'verbose_name_plural': 'Credit Product: Product Features',
                'db_table': 'credit_product_productfeatures',
            },
        ),
        migrations.CreateModel(
            name='CreditProductProductTnCs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='credit_product/images')),
                ('header', ckeditor.fields.RichTextField(verbose_name='Heading')),
                ('paragraph', ckeditor.fields.RichTextField(verbose_name='T&Cs')),
                ('button', models.TextField(default='View', verbose_name='Button Text')),
                ('language', models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English')], default='English', max_length=100)),
            ],
            options={
                'verbose_name': 'Cerdit Product: Product TNCs',
                'verbose_name_plural': 'Credit Product: Product TNCs',
                'db_table': 'credit_product_producttncs',
            },
        ),
        migrations.CreateModel(
            name='CreditProductTwoButtonSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=1000, verbose_name='Heading')),
                ('paragraph1', models.CharField(max_length=1000, verbose_name='Paragraph 1')),
                ('paragraph2', models.CharField(max_length=1000, verbose_name='Paragraph 2')),
                ('button1_text', models.CharField(max_length=1000, verbose_name='Button 1 - Text')),
                ('button1_url', models.TextField(blank=True, max_length=10000)),
                ('button2_url', models.TextField(blank=True, max_length=10000)),
                ('button2_text', models.CharField(blank=True, max_length=1000, verbose_name='Button 2 - Text')),
                ('image', models.ImageField(upload_to='credit_product/images')),
                ('language', models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English')], default='English', max_length=100)),
            ],
            options={
                'verbose_name': 'Credit Product: Section 1 - Two Button',
                'verbose_name_plural': 'Credit Product: Section 1 - Two Button',
                'db_table': 'credit_product_twobuttonsection',
            },
        ),
        migrations.CreateModel(
            name='FAQMetaDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200000)),
                ('language', models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English')], default='English', max_length=100)),
            ],
            options={
                'verbose_name': 'FAQ: Meta Description',
                'db_table': 'faq_meta_description',
            },
        ),
        migrations.CreateModel(
            name='FAQMetaTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(blank=True, max_length=20000)),
                ('language', models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English')], default='English', max_length=100)),
            ],
            options={
                'verbose_name': 'FAQ: Meta Tag',
                'db_table': 'faq_meta_tag',
            },
        ),
        migrations.CreateModel(
            name='FAQPageTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('language', models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English')], default='English', max_length=100)),
            ],
            options={
                'verbose_name': 'FAQ: Page Title',
                'verbose_name_plural': 'FAQ: Page Title',
                'db_table': 'faq_pagetitle',
            },
        ),
        migrations.CreateModel(
            name='FAQQuestionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100000000, verbose_name='Question')),
                ('answer', ckeditor.fields.RichTextField()),
                ('language', models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English')], default='English', max_length=100)),
            ],
            options={
                'verbose_name': 'FAQ: Q&A',
                'verbose_name_plural': 'FAQ: Q&A',
                'db_table': 'faq_questionanswer',
            },
        ),
        migrations.CreateModel(
            name='HomeMetaDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200000)),
                ('language', models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English')], default='English', max_length=100)),
            ],
            options={
                'verbose_name': 'Home: Meta Description',
                'db_table': 'homepage_meta_description',
            },
        ),
        migrations.CreateModel(
            name='HomeMetaTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(blank=True, max_length=20000)),
                ('language', models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English')], default='English', max_length=100)),
            ],
            options={
                'verbose_name': 'Home: Meta Tag',
                'db_table': 'homepage_meta_tag',
            },
        ),
        migrations.CreateModel(
            name='HomePageTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('language', models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English')], default='English', max_length=100)),
            ],
            options={
                'verbose_name': 'Home: Page Title',
                'verbose_name_plural': 'Home: Page Title',
                'db_table': 'homepage_pagetitle',
            },
        ),
        migrations.CreateModel(
            name='HomeSection1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading_1', models.CharField(default='Get Money To Make Money - Quickly, Easily, Clearly', max_length=200)),
                ('heading_2', models.CharField(default='Aap Ka Vishwaas, Humari Takneek', max_length=200)),
                ('subtext', models.CharField(default='It’s simple: we pay your suppliers first, then you repay us later.', max_length=300)),
                ('btn1_text', models.CharField(default='For Shopkeepers', max_length=100)),
                ('btn1_url', models.TextField(max_length=100000)),
                ('btn2_text', models.CharField(default='For Shopkeepers', max_length=100)),
                ('btn2_url', models.TextField(max_length=100000)),
                ('image', models.ImageField(upload_to='homepage/images')),
                ('language', models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English')], default='English', max_length=100)),
            ],
            options={
                'verbose_name': 'Home: First Section - Two Button',
                'verbose_name_plural': 'Home: First Section - Two Button',
                'db_table': 'homepage_section1',
            },
        ),
        migrations.CreateModel(
            name='HomeSection2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading_1', models.CharField(max_length=1000)),
                ('heading_2', models.CharField(blank=True, max_length=1000)),
                ('heading_3', models.CharField(blank=True, max_length=1000)),
                ('url', models.TextField()),
                ('btn_text', models.CharField(max_length=200)),
                ('language', models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English')], default='English', max_length=100)),
            ],
            options={
                'verbose_name': 'Home: Learn More - Information Section',
                'verbose_name_plural': 'Home: Learn More - Information Section',
                'db_table': 'homepage_section2',
            },
        ),
        migrations.CreateModel(
            name='HomeSection3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_text', models.CharField(max_length=10000)),
                ('step_text', models.CharField(max_length=3)),
                ('image', models.ImageField(upload_to='homepage/images/')),
                ('language', models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English')], default='English', max_length=100)),
            ],
            options={
                'verbose_name': 'Home: Steps - Image Carousel Section',
                'verbose_name_plural': 'Home: Steps - Image Carousel Section',
                'db_table': 'homepage_section3',
            },
        ),
        migrations.CreateModel(
            name='HomeSection4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_text', models.CharField(max_length=10000)),
                ('step_text', models.CharField(max_length=3)),
                ('image', models.ImageField(upload_to='homepage/images/')),
                ('url', models.TextField(max_length=100000)),
                ('url_text', models.CharField(max_length=200)),
                ('language', models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English')], default='English', max_length=100)),
            ],
            options={
                'verbose_name': 'Home: How Bridge2Capital Works - Section',
                'verbose_name_plural': 'Home: How Bridge2Capital Works - Section',
                'db_table': 'homepage_section4',
            },
        ),
        migrations.CreateModel(
            name='HomeSection5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=1000, verbose_name='Benefit Header')),
                ('description', models.CharField(max_length=10000, verbose_name='Benefit Description')),
                ('language', models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English')], default='English', max_length=100)),
            ],
            options={
                'verbose_name': 'Home: Benefit',
                'verbose_name_plural': 'Home: Benefits',
                'db_table': 'homepage_section5',
            },
        ),
        migrations.CreateModel(
            name='HomeSection6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='homepage/images/')),
                ('heading', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=1000)),
                ('language', models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English')], default='English', max_length=100)),
            ],
            options={
                'verbose_name': 'Home: Why Bridge2Capital?',
                'verbose_name_plural': 'Home: Why Bridge2Capital?',
                'db_table': 'homepage_section6',
            },
        ),
        migrations.CreateModel(
            name='HomeSection7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='homepage/images')),
                ('name', models.CharField(max_length=1000, verbose_name='Partner Name')),
                ('language', models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English')], default='English', max_length=100)),
            ],
            options={
                'verbose_name': 'Home: Partner',
                'db_table': 'homepage_section7',
            },
        ),
        migrations.CreateModel(
            name='HomeSection8',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(max_length=100000, verbose_name='Video URL')),
                ('name', models.CharField(max_length=1000, verbose_name='Video Name')),
                ('language', models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English')], default='English', max_length=100)),
            ],
            options={
                'verbose_name': 'Home: What our Users are saying',
                'verbose_name_plural': 'Home: What our Users are saying',
                'db_table': 'homepage_section8',
            },
        ),
        migrations.CreateModel(
            name='InvestorsContactForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200, verbose_name='Full Name')),
                ('contactnumber', models.CharField(max_length=12, verbose_name='Contact Number')),
                ('email', models.EmailField(max_length=200, verbose_name='Email Address')),
                ('message', models.CharField(max_length=600, verbose_name='Message')),
                ('language', models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English')], default='English', max_length=100)),
            ],
            options={
                'verbose_name': 'Investors: Contact Form',
                'verbose_name_plural': 'Investors: Contact Form',
                'db_table': 'investors_contactform',
            },
        ),
        migrations.CreateModel(
            name='InvestorsMetaDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200000)),
                ('language', models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English')], default='English', max_length=100)),
            ],
            options={
                'verbose_name': 'Investors: Meta Description',
                'db_table': 'investors_meta_description',
            },
        ),
        migrations.CreateModel(
            name='InvestorsMetaTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(blank=True, max_length=20000)),
                ('language', models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English')], default='English', max_length=100)),
            ],
            options={
                'verbose_name': 'Investors: Meta Tag',
                'db_table': 'investors_meta_tag',
            },
        ),
        migrations.CreateModel(
            name='InvestorsOneButtonBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=1000000, verbose_name='Heading')),
                ('paragraph', models.CharField(max_length=1000000, verbose_name='Paragraph')),
                ('subtext', ckeditor.fields.RichTextField()),
                ('button_text', models.CharField(max_length=100000, verbose_name='Button Text')),
                ('button_url', models.TextField(max_length=100000, verbose_name='Button URL')),
                ('image', models.ImageField(upload_to='investors/images')),
                ('language', models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English')], default='English', max_length=100)),
            ],
            options={
                'verbose_name': 'Investors: First Banner - One Button',
                'verbose_name_plural': 'Investors: First Banner - One Button',
                'db_table': 'investors_onebuttonbanner',
            },
        ),
        migrations.CreateModel(
            name='InvestorsOurApproach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=1000000, verbose_name='Heading')),
                ('paragraph', ckeditor.fields.RichTextField(verbose_name='Paragraph')),
                ('language', models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English')], default='English', max_length=100)),
            ],
            options={
                'verbose_name': 'Investors: Our Approach Banner',
                'verbose_name_plural': 'Investors: Our Approach Banner',
                'db_table': 'investors_ourapproach',
            },
        ),
        migrations.CreateModel(
            name='InvestorsOurBusinessModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=1000000, verbose_name='Heading')),
                ('paragraph', ckeditor.fields.RichTextField(verbose_name='Paragraph')),
                ('image', models.ImageField(upload_to='investors/images')),
                ('language', models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English')], default='English', max_length=100)),
            ],
            options={
                'verbose_name': 'Investors: Our Business Model Banner',
                'verbose_name_plural': 'Investors: Our Business Model Banners',
                'db_table': 'investors_ourbusinessmodel',
            },
        ),
        migrations.CreateModel(
            name='InvestorsOurTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=1000000, verbose_name='Heading')),
                ('paragraph', ckeditor.fields.RichTextField(verbose_name='Paragraph')),
                ('image', models.ImageField(upload_to='investors/images')),
                ('language', models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English')], default='English', max_length=100)),
            ],
            options={
                'verbose_name': 'Investors: Our Team Banner',
                'verbose_name_plural': 'Investors: Our Team Banner',
                'db_table': 'investors_ourteam',
            },
        ),
        migrations.CreateModel(
            name='InvestorsPageTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('language', models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English')], default='English', max_length=100)),
            ],
            options={
                'verbose_name': 'Investors: Page Title',
                'verbose_name_plural': 'Investors: Page Title',
                'db_table': 'investors_pagetitle',
            },
        ),
        migrations.CreateModel(
            name='InvestorsYellowStripSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=1000000, verbose_name='Heading')),
                ('paragraph', ckeditor.fields.RichTextField(verbose_name='Paragraph')),
                ('language', models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English')], default='English', max_length=100)),
            ],
            options={
                'verbose_name': 'Investors: Yellow Strip Banner',
                'verbose_name_plural': 'Investors: Yellow Strip Banner',
                'db_table': 'investors_yellowstripsection',
            },
        ),
        migrations.CreateModel(
            name='PressBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('by_tag', models.CharField(default='By Xtracap India', max_length=1000)),
                ('description', models.CharField(max_length=1000)),
                ('body', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to='news/images/')),
                ('alt_tag', models.CharField(default='Bridge2Capital', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('featured', models.BooleanField(default=False, verbose_name='Featured Post?')),
                ('slug', models.SlugField(max_length=300)),
                ('meta_tags', models.CharField(blank=True, max_length=1000000, verbose_name='Meta Tags')),
                ('meta_description', models.CharField(blank=True, max_length=1000000, verbose_name='Meta Description')),
                ('url', models.TextField(blank=True, max_length=100000)),
                ('language', models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English')], default='English', max_length=100)),
            ],
            options={
                'verbose_name': 'Press: Blog',
                'verbose_name_plural': 'Press: Blog',
                'db_table': 'news_blog',
            },
        ),
        migrations.CreateModel(
            name='PressMetaDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200000)),
                ('language', models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English')], default='English', max_length=100)),
            ],
            options={
                'verbose_name': 'Press: Meta Description',
                'db_table': 'news_meta_description',
            },
        ),
        migrations.CreateModel(
            name='PressMetaTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(blank=True, max_length=20000)),
                ('language', models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English')], default='English', max_length=100)),
            ],
            options={
                'verbose_name': 'Press: Meta Tag',
                'db_table': 'news_meta_tag',
            },
        ),
        migrations.CreateModel(
            name='PressNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('by_tag', models.CharField(default='By Xtracap India', max_length=1000)),
                ('description', models.CharField(max_length=1000)),
                ('body', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to='news/images/')),
                ('url', models.TextField(blank=True, max_length=100000)),
                ('alt_tag', models.CharField(default='Bridge2Capital', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('featured', models.BooleanField(default=False, verbose_name='Featured Post?')),
                ('slug', models.SlugField(max_length=300)),
                ('meta_tags', models.CharField(blank=True, max_length=1000000, verbose_name='Meta Tags')),
                ('meta_description', models.CharField(blank=True, max_length=1000000, verbose_name='Meta Description')),
                ('language', models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English')], default='English', max_length=100)),
            ],
            options={
                'verbose_name': 'Press: News',
                'verbose_name_plural': 'Press: News',
                'db_table': 'news_news',
            },
        ),
        migrations.CreateModel(
            name='PressPageTitleBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('language', models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English')], default='English', max_length=100)),
            ],
            options={
                'verbose_name': 'Press: Blog Page Title',
                'verbose_name_plural': 'Press: Blog Page Title',
                'db_table': 'news_pagetitleblog',
            },
        ),
        migrations.CreateModel(
            name='PressPageTitleNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('language', models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English')], default='English', max_length=100)),
            ],
            options={
                'verbose_name': 'Press: News Page Title',
                'verbose_name_plural': 'Press: News Page Title',
                'db_table': 'news_pagetitlenews',
            },
        ),
        migrations.CreateModel(
            name='PrivacyMetaDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200000)),
                ('language', models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English')], default='English', max_length=100)),
            ],
            options={
                'verbose_name': 'Privacy: Meta Description',
                'db_table': 'privacy_meta_description',
            },
        ),
        migrations.CreateModel(
            name='PrivacyMetaTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(blank=True, max_length=20000)),
                ('language', models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English')], default='English', max_length=100)),
            ],
            options={
                'verbose_name': 'Privacy: Meta Tag',
                'db_table': 'privacy_meta_tag',
            },
        ),
        migrations.CreateModel(
            name='PrivacyPageTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('language', models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English')], default='English', max_length=100)),
            ],
            options={
                'verbose_name': 'Privacy: Page Title',
                'verbose_name_plural': 'Privacy: Page Title',
                'db_table': 'privacy_pagetitle',
            },
        ),
        migrations.CreateModel(
            name='PrivacyPrivacyPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=10000, verbose_name='Heading')),
                ('subheader', ckeditor.fields.RichTextField(verbose_name='Sub Heading')),
                ('paragraph', ckeditor.fields.RichTextField()),
                ('language', models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English')], default='English', max_length=100)),
            ],
            options={
                'verbose_name': 'Privacy: Privacy Policy',
                'verbose_name_plural': 'Privacy: Privacy Policy',
                'db_table': 'privacy_privacypolicy',
            },
        ),
        migrations.CreateModel(
            name='TestimonialsMetaDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200000)),
                ('language', models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English')], default='English', max_length=100)),
            ],
            options={
                'verbose_name': 'Testimonials: Meta Description',
                'db_table': 'testimonials_meta_description',
            },
        ),
        migrations.CreateModel(
            name='TestimonialsMetaTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(blank=True, max_length=20000)),
                ('language', models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English')], default='English', max_length=100)),
            ],
            options={
                'verbose_name': 'Testimonials: Meta Tag',
                'db_table': 'testimonials_meta_tag',
            },
        ),
        migrations.CreateModel(
            name='TestimonialsPageTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('language', models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English')], default='English', max_length=100)),
            ],
            options={
                'verbose_name': 'Testimonials: Page Title',
                'verbose_name_plural': 'Testimonials: Page Title',
                'db_table': 'testimonials_pagetitle',
            },
        ),
        migrations.CreateModel(
            name='TestimonialsSection1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading_1', models.CharField(default='What Business Owners Like You Are Saying', max_length=1000, verbose_name='Heading')),
                ('subtext', models.CharField(default='Listen to what fast-expanding Bridge2Capital family thinks.', max_length=1000, verbose_name='Sub Text')),
                ('image', models.ImageField(upload_to='testimonials/images/')),
                ('language', models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English')], default='English', max_length=100)),
            ],
            options={
                'verbose_name': 'Testimonials: First Section',
                'verbose_name_plural': 'Testimonials: First Section',
                'db_table': 'testimonials_section1',
            },
        ),
        migrations.CreateModel(
            name='TestimonialsTestimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Customer Name')),
                ('category', models.CharField(max_length=1000, verbose_name='Business Type')),
                ('image', models.ImageField(upload_to='testimonials/images/', verbose_name='Customer Image')),
                ('body', models.CharField(max_length=1000, verbose_name='Customer Message')),
                ('description', models.CharField(max_length=1000, verbose_name='Message Snippet (For Homepage)')),
                ('language', models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English')], default='English', max_length=100)),
            ],
            options={
                'verbose_name': 'Testimonials: Testimonial',
                'verbose_name_plural': 'Testimonials: Testimonials',
                'db_table': 'testimonials_testimonial',
            },
        ),
        migrations.CreateModel(
            name='TNCMetaDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200000)),
                ('language', models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English')], default='English', max_length=100)),
            ],
            options={
                'verbose_name': 'TNC: Meta Description',
                'db_table': 'terms_conditions_meta_description',
            },
        ),
        migrations.CreateModel(
            name='TNCMetaTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(blank=True, max_length=20000)),
                ('language', models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English')], default='English', max_length=100)),
            ],
            options={
                'verbose_name': 'TNC: Meta Tag',
                'db_table': 'terms_conditions_meta_tag',
            },
        ),
        migrations.CreateModel(
            name='TNCPageTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('language', models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English')], default='English', max_length=100)),
            ],
            options={
                'verbose_name': 'TNC: Page Title',
                'verbose_name_plural': 'TNC: Page Title',
                'db_table': 'terms_conditions_pagetitle',
            },
        ),
        migrations.CreateModel(
            name='TNCTermsConditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=10000, verbose_name='Heading')),
                ('subheader', ckeditor.fields.RichTextField(verbose_name='Sub Heading')),
                ('paragraph', ckeditor.fields.RichTextField()),
                ('language', models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English')], default='English', max_length=100)),
            ],
            options={
                'verbose_name': 'TNC: Terms & Conditions',
                'verbose_name_plural': 'TNC: Terms & Conditions',
                'db_table': 'terms_conditions_termsconditions',
            },
        ),
    ]
